=== lauflulu/PeriodDoubling/lib/Config/validator.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!--This section defines the data types for later configuration commands-->
	<xs:element name="Measurement">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Configuration" minOccurs="0">
					<xs:complexType>
						<xs:sequence>			
							<xs:element name="Stage" type="_stage" minOccurs="0" maxOccurs="1"/>
							<xs:element name="Microscope" type="_microscope" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Loop">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Duration" type="_duration" minOccurs="0"/>
							<xs:element name="Image" type="_img" minOccurs="0"/>								
							<xs:element name="Microscope" type="_microscope" minOccurs="0" maxOccurs="6"/>
							<xs:element name="Position" type="_position" minOccurs="0" maxOccurs="unbounded"/>				
							<xs:element name="Program" type="_arduino" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:simpleType name="_posX">
		<xs:restriction base="xs:decimal">
			<!-- TODO Find out the maximum-->
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_posY">
		<xs:restriction base="xs:decimal">
			<!-- TODO Find out the maximum-->
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_vel_acc">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0.1"/>
			<xs:maxInclusive value="20.00"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Defines elements for the microscope element-->

	<xs:simpleType name="_obj">
		<xs:restriction base="xs:integer">
			<xs:enumeration value="4"/>
			<xs:enumeration value="10"/>
			<xs:enumeration value="20"/>
			<xs:enumeration value="40"/>
			<xs:enumeration value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_filter">
		<xs:restriction base="xs:string">
			<xs:enumeration value="UV"/>
			<xs:enumeration value="Cy5"/>
			<xs:enumeration value="RFP"/>
			<xs:enumeration value="CFP"/>
			<xs:enumeration value="GFP"/>
			<xs:enumeration value="BF"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_prism">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Bi"/>
			<xs:enumeration value="Side"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_percent">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_focus">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="3000000.00"/>
		</xs:restriction>
	</xs:simpleType>


	<!-- Indicates the duration of a measurement-->
	<xs:simpleType name="_duration">
    <xs:restriction base="xs:time">
        <xs:pattern value="[0-2][0-9]:[0-5][0-9]:[0-5][0-9]"/>
    </xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="_elveflowChannel">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="4"/>
		</xs:restriction>
	</xs:simpleType>




	<!-- Indicates the name, saving directory and aquisition interval of an automatized measurement-->
	<xs:complexType name="_img">
		<xs:all>
			<xs:element name="Prefix" type="xs:string"/>
			<xs:element name="AcquisitionInterval" type="xs:time"/>
			<xs:element name="SaveDir" type="xs:string"/>
		</xs:all>
	</xs:complexType>


	<!-- Container for Stage Configuration-->
	<xs:complexType name="_stage">
		<xs:all>
			<xs:element name="VelocityX" type="_vel_acc" />
			<xs:element name="VelocityY" type="_vel_acc"/>
			<xs:element name="AccelerationX" type="_vel_acc"/>
			<xs:element name="AccelerationY" type="_vel_acc"/>
		</xs:all>
	</xs:complexType>

	<!-- Container for microscope Configuration-->
	<xs:complexType name="_microscope">
		<xs:sequence>
			<xs:element name="Objective" type="_obj"/>
			<xs:element name="Filter" type="_filter"/>
			<xs:element name="Prism" type="_prism"/>
			<xs:element name="Intensity" type="_percent"/>
			<xs:element name="Exposure" type="xs:decimal" />			
		</xs:sequence>
	</xs:complexType>

	<!-- Container for different valve configuration-->
	<xs:complexType name="_arduino">
		<xs:choice maxOccurs="50">
			<xs:element name="Feed" type="_feed"/>
      <xs:element name="Pump" type="_pump"/>
      <xs:element name="ChangeReagent" type="_changeReagent"/>
      <xs:element name="Incubate" type="_duration"/>
      <xs:element name="IterationStart" type="_iterationStart"/>
      <xs:element name="IterationEnd" type="xs:decimal"/>
      <xs:element name="Acquire" type="_acquire"/>
    </xs:choice>
	</xs:complexType>


	<xs:complexType name="_position">
		<xs:sequence>
			<xs:element name="X" type="_posX"/>
			<xs:element name="Y" type="_posY"/>		
			<xs:element name="Focus" type="_focus"/>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="_pump">
		<xs:sequence>
			<xs:element name="Duration" type="_duration"/>
			<xs:element name="Frequency" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>

  <xs:complexType name="_feed">
    <xs:sequence>
      <xs:element name="Ratio" type="_percent"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="_changeReagent">
    <xs:sequence>
      <xs:element name="Duration" type="_duration"/>
      <xs:element name="ReagentNr" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="_iterationStart">
    <xs:sequence>
      <xs:element name="ID" type="xs:integer"/>
      <xs:element name="Iterations" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>

    <xs:complexType name="_acquire"/>

  
</xs:schema>

=== lauflulu/PeriodDoubling/Config_Files/200305_micro.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\lib\Config\validator.xsd"><Loop>
<Microscope>
<Objective>10</Objective>
<Filter>BF</Filter>
<Prism>Side</Prism>
<Intensity>12.5</Intensity>
<Exposure>50</Exposure>
</Microscope>
<Microscope>
<Objective>10</Objective>
<Filter>GFP</Filter>
<Prism>Side</Prism>
<Intensity>5.0</Intensity>
<Exposure>200</Exposure>
</Microscope>
<Microscope>
<Objective>10</Objective>
<Filter>CFP</Filter>
<Prism>Side</Prism>
<Intensity>5.0</Intensity>
<Exposure>200</Exposure>
</Microscope>
<Microscope>
<Objective>10</Objective>
<Filter>YFP</Filter>
<Prism>Side</Prism>
<Intensity>5.0</Intensity>
<Exposure>200</Exposure>
</Microscope>
<Microscope>
<Objective>10</Objective>
<Filter>RFP</Filter>
<Prism>Side</Prism>
<Intensity>5.0</Intensity>
<Exposure>200</Exposure>
</Microscope>
</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/instrument-control/Config_Files/200224_test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\lib\Config\validator.xsd"><Loop>
<Duration>15:03:00</Duration>
<Image>
<Prefix>img</Prefix>
<AcquisitionInterval>00:00:23</AcquisitionInterval>
<SaveDir>C:\Users\e14user\Documents\LabVIEW software\GitRepo\Config_Files\TestFolder</SaveDir>
</Image>
<Program>
<Feed>
<Ratio>20</Ratio>
<Ring>1</Ring>
</Feed>
</Program>
</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/instrument-control/Config_Files/191127_full_test_final.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\lib\Config\validator.xsd">
	<Loop>
		<Duration>00:30:00</Duration>
		<Image>
			<Prefix>img</Prefix>
			<AcquisitionInterval>00:03:00</AcquisitionInterval>
			<SaveDir>C:\Users\e14user\Documents\LabVIEW software\GitRepo\Config_Files</SaveDir>
		</Image>
		<Microscope>
			<Objective>20</Objective>
			<Filter>BF</Filter>
			<Prism>Side</Prism>
			<Intensity>13.3</Intensity>
			<Exposure>50</Exposure>
		</Microscope>
		<Microscope>
			<Objective>20</Objective>
			<Filter>GFP</Filter>
			<Prism>Side</Prism>
			<Intensity>40.0</Intensity>
			<Exposure>300</Exposure>
		</Microscope>
		<Position>
			<X>-527.4</X>
			<Y>-44.0</Y>
			<Focus>435.33</Focus>
		</Position>
		<Position>
			<X>-927.4</X>
			<Y>-44.0</Y>
			<Focus>435.33</Focus>
		</Position>
		<Position>
			<X>-1327.4</X>
			<Y>-44.0</Y>
			<Focus>435.33</Focus>
		</Position>
		<Position>
			<X>-1327.4</X>
			<Y>756.0</Y>
			<Focus>435.33</Focus>
		</Position>
		<Position>
			<X>-2727.4</X>
			<Y>456.0</Y>
			<Focus>439.58</Focus>
		</Position>
		<Position>
			<X>-2727.4</X>
			<Y>456.0</Y>
			<Focus>433.24</Focus>
		</Position>
		<Program>
			<Feed>
				<Ratio>33</Ratio>
			</Feed>
			<ChangeReagent>
				<Duration>00:00:05</Duration>
				<ReagentNr>3</ReagentNr>
			</ChangeReagent>
			<Pump>
				<Duration>00:00:10</Duration>
				<Frequency>7</Frequency>
			</Pump>
			<IterationStart>
				<ID>0</ID>
				<Iterations>20</Iterations>
			</IterationStart>
			<Pump>
				<Duration>00:00:10</Duration>
				<Frequency>8</Frequency>
			</Pump>
			<Incubate>00:00:20</Incubate>
			<Acquire />
			<Feed>
				<Ratio>10</Ratio>
			</Feed>
			<IterationEnd>0</IterationEnd>
		</Program>
	</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/Config_Files/191127_zlast_test_fullprogram.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\lib\Config\validator.xsd"><Loop>
<Duration>00:30:00</Duration>
<Image>
<Prefix>zlast_test_img.tif</Prefix>
<AcquisitionInterval>00:01:00</AcquisitionInterval>
<SaveDir>C:\Users\e14user\Documents\LabVIEW software\GitRepo\Config_Files\TestFolder</SaveDir>
</Image>
<Microscope>
<Objective>20</Objective>
<Filter>BF</Filter>
<Prism>Side</Prism>
<Intensity>10.0</Intensity>
<Exposure>50</Exposure>
</Microscope>
<Microscope>
<Objective>20</Objective>
<Filter>GFP</Filter>
<Prism>Side</Prism>
<Intensity>50.0</Intensity>
<Exposure>500</Exposure>
</Microscope>
<Position>
<X>610.8</X>
<Y>0.0</Y>
<Focus>434.86</Focus>
</Position>
<Position>
<X>2236.9</X>
<Y>-482.1</Y>
<Focus>434.86</Focus>
</Position>
<Position>
<X>2236.9</X>
<Y>682.3</Y>
<Focus>434.86</Focus>
</Position>
<Program>
<IterationStart>
<ID>0</ID>
<Iterations>3</Iterations>
</IterationStart>
<Pump>
<Duration>00:00:15</Duration>
<Frequency>8</Frequency>
</Pump>
<Feed>
<Ratio>10</Ratio>
</Feed>
<Incubate>00:00:20</Incubate>
<ChangeReagent>
<Duration>00:00:05</Duration>
<ReagentNr>1</ReagentNr>
</ChangeReagent>
<Acquire />
<IterationEnd>0</IterationEnd>
</Program>
</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/data-and-simulation/210518_program_osci_woIN.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\LabViewDevelopment\lib\Config\validator.xsd">
	<Loop>
		<Duration>24:00:00</Duration>
		<Image>
			<Prefix>s28osci_woIN</Prefix>
			<AcquisitionInterval>00:15:00</AcquisitionInterval>
			<SaveDir>C:\Users\e14user\data\laufinger\210518_s28osci_woIN\210518_images</SaveDir>
		</Image>
		<Microscope>
			<Objective>10</Objective>
			<Filter>BF</Filter>
			<Prism>Side</Prism>
			<Intensity>15.0</Intensity>
			<Exposure>100</Exposure>
		</Microscope>
		<Microscope>
			<Objective>10</Objective>
			<Filter>CFP</Filter>
			<Prism>Side</Prism>
			<Intensity>50</Intensity>
			<Exposure>500</Exposure>
		</Microscope>
		<Microscope>
			<Objective>10</Objective>
			<Filter>YFP</Filter>
			<Prism>Side</Prism>
			<Intensity>50</Intensity>
			<Exposure>500</Exposure>
		</Microscope>
		<Position>
<X>8806.400</X>
<Y>18453.900</Y>
<Focus>390.14</Focus>
</Position>
<Position>
<X>8806.400</X>
<Y>16560.500</Y>
<Focus>390.14</Focus>
</Position>
<Position>
<X>8978.100</X>
<Y>14638.800</Y>
<Focus>391.45</Focus>
</Position>
<Position>
<X>8978.100</X>
<Y>12801.700</Y>
<Focus>391.45</Focus>
</Position>
<Position>
<X>9078.800</X>
<Y>10852.400</Y>
<Focus>392.80</Focus>
</Position>
<Position>
<X>9078.800</X>
<Y>8972.600</Y>
<Focus>392.80</Focus>
</Position>
<Position>
<X>9078.800</X>
<Y>7029.200</Y>
<Focus>394.85</Focus>
</Position>
<Position>
<X>9078.800</X>
<Y>5141.400</Y>
<Focus>394.85</Focus>
</Position>

		<Program>




			<IterationStart>
				<ID>1</ID>
				<Iterations>100</Iterations>
			</IterationStart>

			<Incubate>00:00:02</Incubate>

			<!--EXTRACT-->

			<FlushFeed>
				<ReagentNr>4</ReagentNr>
				<Cycles>100</Cycles>	
			</FlushFeed>
			<Feed>
				<Ratio>5</Ratio>
				<Ring>1</Ring>
			</Feed>
			<Feed>
				<Ratio>7.5</Ratio>
				<Ring>2</Ring>
			</Feed>
			<Feed>
				<Ratio>10</Ratio>
				<Ring>3</Ring>
			</Feed>
			<Feed>
				<Ratio>12.5</Ratio>
				<Ring>4</Ring>
			</Feed>
			<Feed>
				<Ratio>15</Ratio>
				<Ring>5</Ring>
			</Feed>
			<Feed>
				<Ratio>12.5</Ratio>
				<Ring>6</Ring>
			</Feed>
			<Feed>
				<Ratio>10</Ratio>
				<Ring>7</Ring>
			</Feed>
			<Feed>
				<Ratio>7.5</Ratio>
				<Ring>8</Ring>
			</Feed>

			<Incubate>00:00:02</Incubate>

			<!--BUFFER+DNA-->
			<FlushFeed>
				<ReagentNr>3</ReagentNr>
				<Cycles>100</Cycles>	
			</FlushFeed>
			<Feed>
				<Ratio>5</Ratio>
				<Ring>1</Ring>
			</Feed>
			<Feed>
				<Ratio>7.5</Ratio>
				<Ring>2</Ring>
			</Feed>
			<Feed>
				<Ratio>10</Ratio>
				<Ring>3</Ring>
			</Feed>
			<Feed>
				<Ratio>12.5</Ratio>
				<Ring>4</Ring>
			</Feed>
			<Feed>
				<Ratio>15</Ratio>
				<Ring>5</Ring>
			</Feed>
			<Feed>
				<Ratio>12.5</Ratio>
				<Ring>6</Ring>
			</Feed>
			<Feed>
				<Ratio>10</Ratio>
				<Ring>7</Ring>
			</Feed>
			<Feed>
				<Ratio>7.5</Ratio>
				<Ring>8</Ring>
			</Feed>


			<Incubate>00:00:02</Incubate>

			<!--Flush with water-->
			<ChangeReagent>
				<Duration>00:00:30</Duration>
				<ReagentNr>1</ReagentNr>
			</ChangeReagent>
			<!--Mix-->
			<Incubate>00:00:02</Incubate>
			<Mix>00:05:00</Mix>
			<Incubate>00:00:02</Incubate>
			<!--Acquire-->
			<Acquire/>
			<Incubate>00:00:02</Incubate>

			<IterationEnd>1</IterationEnd>



		</Program>
	</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/instrument-control/Config_Files/200302_TestProgram_DilutionSeries_0.1-0.7.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\lib\Config\validator.xsd"><Loop>
<Duration>12:00:00</Duration>
<Image>
<Prefix>DilSeries_</Prefix>
<AcquisitionInterval>00:10:00</AcquisitionInterval>
<SaveDir>C:\Users\e14user\Documents\LabVIEW software\GitRepo\Test_N_Eval_Images\200302_DilSeries1_Test</SaveDir>
</Image>
<Microscope>
<Objective>4</Objective>
<Filter>GFP</Filter>
<Prism>Side</Prism>
<Intensity>20.0</Intensity>
<Exposure>200</Exposure>
</Microscope>
<Microscope>
<Objective>4</Objective>
<Filter>BF</Filter>
<Prism>Side</Prism>
<Intensity>12.5</Intensity>
<Exposure>50</Exposure>
</Microscope>
<Position>
<X>-15416.600</X>
<Y>8806.800</Y>
<Focus>408.60</Focus>
</Position>
<Position>
<X>-15416.600</X>
<Y>6947.500</Y>
<Focus>408.60</Focus>
</Position>
<Position>
<X>-15416.600</X>
<Y>4889.000</Y>
<Focus>408.60</Focus>
</Position>
<Position>
<X>-15416.600</X>
<Y>2875.200</Y>
<Focus>408.60</Focus>
</Position>
<Position>
<X>-15416.600</X>
<Y>1170.500</Y>
<Focus>408.60</Focus>
</Position>
<Position>
<X>-15416.600</X>
<Y>-777.100</Y>
<Focus>408.60</Focus>
</Position>
<Position>
<X>-15416.600</X>
<Y>-2693.000</Y>
<Focus>408.60</Focus>
</Position>
<Position>
<X>-15416.600</X>
<Y>-4553.100</Y>
<Focus>408.60</Focus>
</Position>
<Position>
<X>-18700.800</X>
<Y>2941.100</Y>
<Focus>408.00</Focus>
</Position>
<Position>
<X>-11486.400</X>
<Y>2340.200</Y>
<Focus>408.00</Focus>
</Position>
<Program>
<IterationStart>
<ID>0</ID>
<Iterations>30</Iterations>
</IterationStart>
<ChangeReagent>
<Duration>00:00:02</Duration>
<ReagentNr>2</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>10</Ratio>
<Ring>2</Ring>
</Feed>
<Feed>
<Ratio>20</Ratio>
<Ring>3</Ring>
</Feed>
<Feed>
<Ratio>30</Ratio>
<Ring>4</Ring>
</Feed>
<Feed>
<Ratio>40</Ratio>
<Ring>5</Ring>
</Feed>
<Feed>
<Ratio>50</Ratio>
<Ring>6</Ring>
</Feed>
<Feed>
<Ratio>60</Ratio>
<Ring>7</Ring>
</Feed>
<Feed>
<Ratio>70</Ratio>
<Ring>8</Ring>
</Feed>
<Incubate>00:05:00</Incubate>
<Acquire />
<IterationEnd>0</IterationEnd>
</Program>
</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/instrument-control/Config_Files/200302_TestProgram_Acquisition.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\lib\Config\validator.xsd"><Loop>
<Duration>00:10:00</Duration>
<Image>
<Prefix />
<AcquisitionInterval>00:01:30</AcquisitionInterval>
<SaveDir>C:\Users\e14user\Documents\LabVIEW software\GitRepo\Test_N_Eval_Images\200303_AcquTest</SaveDir>
</Image>
<Microscope>
<Objective>4</Objective>
<Filter>GFP</Filter>
<Prism>Side</Prism>
<Intensity>20.0</Intensity>
<Exposure>200</Exposure>
</Microscope>
<Microscope>
<Objective>4</Objective>
<Filter>BF</Filter>
<Prism>Side</Prism>
<Intensity>12.5</Intensity>
<Exposure>50</Exposure>
</Microscope>
<Position>
<X>-170.100</X>
<Y>-31787.700</Y>
<Focus>407.59</Focus>
</Position>
<Position>
<X>-170.100</X>
<Y>-35084.900</Y>
<Focus>407.59</Focus>
</Position>
<Position>
<X>-170.100</X>
<Y>-39462.300</Y>
<Focus>407.59</Focus>
</Position>
<Program>
<IterationStart>
<ID>0</ID>
<Iterations>5</Iterations>
</IterationStart>
<Acquire />
<Incubate>00:00:30</Incubate>
<IterationEnd>0</IterationEnd>
</Program>
</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/Config_Files/200310_pR_mS_DilSeries.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\lib\Config\validator.xsd"><Loop>
<Duration>23:59:00</Duration>
<Image>
<Prefix>pR_mS</Prefix>
<AcquisitionInterval>00:15:00</AcquisitionInterval>
<SaveDir>C:\Users\e14user\data\jbrenner\200310_pRmS_run2</SaveDir>
</Image>
<Microscope>
<Objective>4</Objective>
<Filter>BF</Filter>
<Prism>Side</Prism>
<Intensity>12.5</Intensity>
<Exposure>300</Exposure>
</Microscope>
<Microscope>
<Objective>4</Objective>
<Filter>Cy5</Filter>
<Prism>Side</Prism>
<Intensity>20.0</Intensity>
<Exposure>500</Exposure>
</Microscope>
<Microscope>
<Objective>4</Objective>
<Filter>CFP</Filter>
<Prism>Side</Prism>
<Intensity>20.0</Intensity>
<Exposure>500</Exposure>
</Microscope>
<Microscope>
<Objective>4</Objective>
<Filter>YFP</Filter>
<Prism>Side</Prism>
<Intensity>20.0</Intensity>
<Exposure>500</Exposure>
</Microscope>
<Microscope>
<Objective>4</Objective>
<Filter>RFP</Filter>
<Prism>Side</Prism>
<Intensity>50.0</Intensity>
<Exposure>500</Exposure>
</Microscope>
<Position>
<X>980.400</X>
<Y>13331.500</Y>
<Focus>415.30</Focus>
</Position>
<Position>
<X>980.400</X>
<Y>11453.500</Y>
<Focus>415.30</Focus>
</Position>
<Position>
<X>980.400</X>
<Y>9582.800</Y>
<Focus>415.30</Focus>
</Position>
<Position>
<X>980.400</X>
<Y>7895.900</Y>
<Focus>415.30</Focus>
</Position>
<Position>
<X>980.400</X>
<Y>5771.000</Y>
<Focus>415.30</Focus>
</Position>
<Position>
<X>378.600</X>
<Y>4057.900</Y>
<Focus>415.30</Focus>
</Position>
<Position>
<X>378.600</X>
<Y>1920.600</Y>
<Focus>415.30</Focus>
</Position>
<Position>
<X>378.600</X>
<Y>-73.800</Y>
<Focus>415.30</Focus>
</Position>
<Program>
<IterationStart>
<ID>0</ID>
<Iterations>100</Iterations>
</IterationStart>
<ChangeReagent>
<Duration>00:00:05</Duration>
<ReagentNr>5</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>15</Ratio>
<Ring>1</Ring>
</Feed>
<Feed>
<Ratio>18.750000</Ratio>
<Ring>2</Ring>
</Feed>
<Feed>
<Ratio>22.5000</Ratio>
<Ring>3</Ring>
</Feed>
<Feed>
<Ratio>26.250000</Ratio>
<Ring>4</Ring>
</Feed>
<Feed>
<Ratio>30.000000</Ratio>
<Ring>5</Ring>
</Feed>
<Feed>
<Ratio>33.750000</Ratio>
<Ring>6</Ring>
</Feed>
<Feed>
<Ratio>37.500000</Ratio>
<Ring>7</Ring>
</Feed>
<Feed>
<Ratio>22.500000</Ratio>
<Ring>8</Ring>
</Feed>
<Incubate>00:00:10</Incubate>
<Acquire />
<ChangeReagent>
<Duration>00:00:05</Duration>
<ReagentNr>4</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>5.000000</Ratio>
<Ring>1</Ring>
</Feed>
<Feed>
<Ratio>6.250000</Ratio>
<Ring>2</Ring>
</Feed>
<Feed>
<Ratio>7.500000</Ratio>
<Ring>3</Ring>
</Feed>
<Feed>
<Ratio>8.750000</Ratio>
<Ring>4</Ring>
</Feed>
<Feed>
<Ratio>10.000000</Ratio>
<Ring>5</Ring>
</Feed>
<Feed>
<Ratio>11.250000</Ratio>
<Ring>6</Ring>
</Feed>
<Feed>
<Ratio>12.500000</Ratio>
<Ring>7</Ring>
</Feed>
<ChangeReagent>
<Duration>00:00:05</Duration>
<ReagentNr>6</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>7.500000</Ratio>
<Ring>8</Ring>
</Feed>
<Incubate>00:00:10</Incubate>
<Acquire />
<Pump>00:04:10</Pump>
<Incubate>00:00:10</Incubate>
<Acquire />
<IterationEnd>0</IterationEnd>
</Program>
</Loop>
</Measurement>
