=== lauflulu/PeriodDoubling/lib/Config/validator.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!--This section defines the data types for later configuration commands-->
	<xs:element name="Measurement">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Configuration" minOccurs="0">
					<xs:complexType>
						<xs:sequence>			
							<xs:element name="Stage" type="_stage" minOccurs="0" maxOccurs="1"/>
							<xs:element name="Microscope" type="_microscope" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Loop">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Duration" type="_duration" minOccurs="0"/>
							<xs:element name="Image" type="_img" minOccurs="0"/>								
							<xs:element name="Microscope" type="_microscope" minOccurs="0" maxOccurs="6"/>
							<xs:element name="Position" type="_position" minOccurs="0" maxOccurs="unbounded"/>				
							<xs:element name="Program" type="_arduino" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:simpleType name="_posX">
		<xs:restriction base="xs:decimal">
			<!-- TODO Find out the maximum-->
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_posY">
		<xs:restriction base="xs:decimal">
			<!-- TODO Find out the maximum-->
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_vel_acc">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0.1"/>
			<xs:maxInclusive value="20.00"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Defines elements for the microscope element-->

	<xs:simpleType name="_obj">
		<xs:restriction base="xs:integer">
			<xs:enumeration value="4"/>
			<xs:enumeration value="10"/>
			<xs:enumeration value="20"/>
			<xs:enumeration value="40"/>
			<xs:enumeration value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_filter">
		<xs:restriction base="xs:string">
			<xs:enumeration value="UV"/>
			<xs:enumeration value="Cy5"/>
			<xs:enumeration value="RFP"/>
			<xs:enumeration value="CFP"/>
			<xs:enumeration value="GFP"/>
			<xs:enumeration value="BF"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_prism">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Bi"/>
			<xs:enumeration value="Side"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_percent">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_focus">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="3000000.00"/>
		</xs:restriction>
	</xs:simpleType>


	<!-- Indicates the duration of a measurement-->
	<xs:simpleType name="_duration">
    <xs:restriction base="xs:time">
        <xs:pattern value="[0-2][0-9]:[0-5][0-9]:[0-5][0-9]"/>
    </xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="_elveflowChannel">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="4"/>
		</xs:restriction>
	</xs:simpleType>




	<!-- Indicates the name, saving directory and aquisition interval of an automatized measurement-->
	<xs:complexType name="_img">
		<xs:all>
			<xs:element name="Prefix" type="xs:string"/>
			<xs:element name="AcquisitionInterval" type="xs:time"/>
			<xs:element name="SaveDir" type="xs:string"/>
		</xs:all>
	</xs:complexType>


	<!-- Container for Stage Configuration-->
	<xs:complexType name="_stage">
		<xs:all>
			<xs:element name="VelocityX" type="_vel_acc" />
			<xs:element name="VelocityY" type="_vel_acc"/>
			<xs:element name="AccelerationX" type="_vel_acc"/>
			<xs:element name="AccelerationY" type="_vel_acc"/>
		</xs:all>
	</xs:complexType>

	<!-- Container for microscope Configuration-->
	<xs:complexType name="_microscope">
		<xs:sequence>
			<xs:element name="Objective" type="_obj"/>
			<xs:element name="Filter" type="_filter"/>
			<xs:element name="Prism" type="_prism"/>
			<xs:element name="Intensity" type="_percent"/>
			<xs:element name="Exposure" type="xs:decimal" />			
		</xs:sequence>
	</xs:complexType>

	<!-- Container for different valve configuration-->
	<xs:complexType name="_arduino">
		<xs:choice maxOccurs="50">
			<xs:element name="Feed" type="_feed"/>
      <xs:element name="Pump" type="_pump"/>
      <xs:element name="ChangeReagent" type="_changeReagent"/>
      <xs:element name="Incubate" type="_duration"/>
      <xs:element name="IterationStart" type="_iterationStart"/>
      <xs:element name="IterationEnd" type="xs:decimal"/>
      <xs:element name="Acquire" type="_acquire"/>
    </xs:choice>
	</xs:complexType>


	<xs:complexType name="_position">
		<xs:sequence>
			<xs:element name="X" type="_posX"/>
			<xs:element name="Y" type="_posY"/>		
			<xs:element name="Focus" type="_focus"/>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="_pump">
		<xs:sequence>
			<xs:element name="Duration" type="_duration"/>
			<xs:element name="Frequency" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>

  <xs:complexType name="_feed">
    <xs:sequence>
      <xs:element name="Ratio" type="_percent"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="_changeReagent">
    <xs:sequence>
      <xs:element name="Duration" type="_duration"/>
      <xs:element name="ReagentNr" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="_iterationStart">
    <xs:sequence>
      <xs:element name="ID" type="xs:integer"/>
      <xs:element name="Iterations" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>

    <xs:complexType name="_acquire"/>

  
</xs:schema>

=== lauflulu/PeriodDoubling/Config_Files/00test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\Familie\Documents\LabviewIX81\lib\Config\validator.xsd">
<Loop>
<Duration>01:26:00</Duration>
<Image>
<Prefix>rur</Prefix>
<AcquisitionInterval>00:07:33</AcquisitionInterval>
<SaveDir>C:\Users\Familie\Documents\LabviewIX81\Config_Files</SaveDir>
</Image>
<Microscope>
<Objective>20</Objective>
<Filter>BF</Filter>
<Prism>Side</Prism>
<Intensity>9.5</Intensity>
<Exposure>50</Exposure>
</Microscope>
<Microscope>
<Objective>20</Objective>
<Filter>GFP</Filter>
<Prism>Side</Prism>
<Intensity>2.5</Intensity>
<Exposure>150</Exposure>
</Microscope>
<Position>
<X>60415.1</X>
<Y>40337.1</Y>
<Focus>419.78</Focus>
</Position>
<Position>
<X>57455.3</X>
<Y>43292.3</Y>
<Focus>419.78</Focus>
</Position>
<Position>
<X>57455.3</X>
<Y>43292.3</Y>
<Focus>408.78</Focus>
</Position>
<Program>
<IterationStart>
<ID>0</ID>
<Iterations>1</Iterations>
</IterationStart>
<ChangeReagent>
<Duration>00:08:50</Duration>
<ReagentNr>3</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>0.000000</Ratio>
<Ring>5</Ring>
</Feed>
<IterationEnd>0</IterationEnd>
</Program>
</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/Config_Files/200423_TestLukas.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\LabViewDevelopment\lib\Config\validator.xsd">
<Loop>
<Duration>00:34:00</Duration>
<Image>
<Prefix>2345</Prefix>
<AcquisitionInterval>00:03:54</AcquisitionInterval>
<SaveDir>C:\Users\e14user\Documents\LabVIEW software</SaveDir>
</Image>
<Program>
<ChangeReagent>
<Duration>00:00:10</Duration>
<ReagentNr>2</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>25.000000</Ratio>
<Ring>2</Ring>
</Feed>
<ChangeReagent>
<Duration>00:00:10</Duration>
<ReagentNr>3</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>25.000000</Ratio>
<Ring>7</Ring>
</Feed>
<IterationStart>
<ID>1</ID>
<Iterations>200</Iterations>
</IterationStart>
<ChangeReagent>
<Duration>00:00:30</Duration>
<ReagentNr>4</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>15.000000</Ratio>
<Ring>1</Ring>
</Feed>
<Feed>
<Ratio>15.000000</Ratio>
<Ring>8</Ring>
</Feed>
<Feed>
<Ratio>15.000000</Ratio>
<Ring>3</Ring>
</Feed>
<Feed>
<Ratio>15.000000</Ratio>
<Ring>4</Ring>
</Feed>
<Feed>
<Ratio>15.000000</Ratio>
<Ring>5</Ring>
</Feed>
<Feed>
<Ratio>15.000000</Ratio>
<Ring>6</Ring>
</Feed>
<Incubate>00:00:10</Incubate>
<Acquire />
<ChangeReagent>
<Duration>00:00:10</Duration>
<ReagentNr>1</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>5.000000</Ratio>
<Ring>8</Ring>
</Feed>
<Feed>
<Ratio>5.000000</Ratio>
<Ring>1</Ring>
</Feed>
<ChangeReagent>
<Duration>00:00:10</Duration>
<ReagentNr>2</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>5.000000</Ratio>
<Ring>3</Ring>
</Feed>
<Feed>
<Ratio>5.000000</Ratio>
<Ring>4</Ring>
</Feed>
<ChangeReagent>
<Duration>00:00:10</Duration>
<ReagentNr>3</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>5.000000</Ratio>
<Ring>5</Ring>
</Feed>
<Feed>
<Ratio>5.000000</Ratio>
<Ring>6</Ring>
</Feed>
<Incubate>00:00:10</Incubate>
<Acquire />
<Mix>00:04:10</Mix>
<Incubate>00:00:10</Incubate>
<Acquire />
<IterationEnd>1</IterationEnd>
</Program>
</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/Config_Files/tmp.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\lib\Config\validator.xsd"><Loop>
<Duration>10:00:00</Duration>
<Image>
<Prefix>bla.tif</Prefix>
<AcquisitionInterval>00:10:00</AcquisitionInterval>
<SaveDir>C:\Users\e14user\Documents\LabVIEW software\GitRepo\Config_Files\TestFolder</SaveDir>
</Image>
<Microscope>
<Objective>20</Objective>
<Filter>BF</Filter>
<Prism>Side</Prism>
<Intensity>10.0</Intensity>
<Exposure>50</Exposure>
</Microscope>
<Microscope>
<Objective>20</Objective>
<Filter>GFP</Filter>
<Prism>Side</Prism>
<Intensity>50.0</Intensity>
<Exposure>500</Exposure>
</Microscope>
<Position>
<X>610.8</X>
<Y>0.0</Y>
<Focus>434.86</Focus>
</Position>
<Position>
<X>2236.9</X>
<Y>-482.1</Y>
<Focus>434.86</Focus>
</Position>
<Position>
<X>2236.9</X>
<Y>682.3</Y>
<Focus>434.86</Focus>
</Position>
<Program>
<IterationStart>
<ID>0</ID>
<Iterations>100</Iterations>
</IterationStart>
<ChangeReagent>
<Duration>00:00:10</Duration>
<ReagentNr>3</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>25</Ratio>
</Feed>
<ChangeReagent>
<Duration>00:00:10</Duration>
<ReagentNr>2</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>5</Ratio>
</Feed>
<Pump>
<Duration>00:05:00</Duration>
<Frequency>10</Frequency>
</Pump>
<Acquire />
<IterationEnd>0</IterationEnd>
</Program>
</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/Config_Files/200310_TestTiming.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\lib\Config\validator.xsd"><Loop>
<Duration>00:10:00</Duration>
<Image>
<Prefix>pRmS_LPT107</Prefix>
<AcquisitionInterval>00:01:00</AcquisitionInterval>
<SaveDir>C:\Users\e14user\Documents\LabVIEW software\GitRepo\Test_N_Eval_Images\200310_TestTiming</SaveDir>
</Image>
<Microscope>
<Objective>10</Objective>
<Filter>BF</Filter>
<Prism>Side</Prism>
<Intensity>12.5</Intensity>
<Exposure>50</Exposure>
</Microscope>
<Position>
<X>51436.000</X>
<Y>44081.000</Y>
<Focus>418.05</Focus>
</Position>
<Program>
<IterationStart>
<ID>0</ID>
<Iterations>2</Iterations>
</IterationStart>
<Pump>00:00:10</Pump>
<Acquire />
<IterationEnd>0</IterationEnd>
</Program>
</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/Config_Files/191127_full_test_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\lib\Config\validator.xsd"><Loop>
<Duration>00:10:00</Duration>
<Image>
<Prefix>img</Prefix>
<AcquisitionInterval>00:01:00</AcquisitionInterval>
<SaveDir>C:\Users\e14user\Documents\LabVIEW software\GitRepo\Config_Files</SaveDir>
</Image>
<Microscope>
<Objective>20</Objective>
<Filter>BF</Filter>
<Prism>Camera</Prism>
<Intensity>9.5</Intensity>
<Exposure>50</Exposure>
</Microscope>
<Microscope>
<Objective>20</Objective>
<Filter>GFP</Filter>
<Prism>Camera</Prism>
<Intensity>2.5</Intensity>
<Exposure>150</Exposure>
</Microscope>
<Position>
<X>60415.1</X>
<Y>40337.1</Y>
<Focus>419.78</Focus>
</Position>
<Position>
<X>57455.3</X>
<Y>43292.3</Y>
<Focus>419.78</Focus>
</Position>
<Position>
<X>57455.3</X>
<Y>43292.3</Y>
<Focus>408.78</Focus>
</Position>
<Program>
<Pump>
<Duration>00:00:10</Duration>
<Frequency>8</Frequency>
</Pump>
<Pump>
<Duration>00:00:10</Duration>
<Frequency>12</Frequency>
</Pump>
<Feed>
<Ratio>10</Ratio>
</Feed>
<IterationStart>
<ID>0</ID>
<Iterations>3</Iterations>
</IterationStart>
<Pump>
<Duration>00:00:12</Duration>
<Frequency>8</Frequency>
</Pump>
<Incubate>00:00:10</Incubate>
<Acquire />
<IterationEnd>0</IterationEnd>
</Program>
</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/Config_Files/191127_full_test_final.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\lib\Config\validator.xsd"><Loop>
<Duration>01:00:00</Duration>
<Image>
<Prefix>img</Prefix>
<AcquisitionInterval>00:01:00</AcquisitionInterval>
<SaveDir>C:\Users\e14user\Documents\LabVIEW software\GitRepo\Config_Files</SaveDir>
</Image>
<Microscope>
<Objective>Objective</Objective>
<Filter>20</Filter>
<Prism>Filter</Prism>
<Intensity>BF</Intensity>
<Exposure>Prism</Exposure>
</Microscope>
<Microscope>
<Objective>Objective</Objective>
<Filter>20</Filter>
<Prism>Filter</Prism>
<Intensity>GFP</Intensity>
<Exposure>Prism</Exposure>
</Microscope>
<Position>
<X>-527.4</X>
<Y>-44.0</Y>
<Focus>435.33</Focus>
</Position>
<Position>
<X>-927.4</X>
<Y>-44.0</Y>
<Focus>435.33</Focus>
</Position>
<Position>
<X>-1327.4</X>
<Y>-44.0</Y>
<Focus>435.33</Focus>
</Position>
<Position>
<X>-1327.4</X>
<Y>756.0</Y>
<Focus>435.33</Focus>
</Position>
<Position>
<X>-2727.4</X>
<Y>456.0</Y>
<Focus>439.58</Focus>
</Position>
<Position>
<X>-2727.4</X>
<Y>456.0</Y>
<Focus>433.24</Focus>
</Position>
<Program>
<Pump>
<Duration>00:00:05</Duration>
<Frequency>8</Frequency>
</Pump>
<Pump>
<Duration>00:00:05</Duration>
<Frequency>12</Frequency>
</Pump>
<Feed>
<Ratio>10</Ratio>
</Feed>
<IterationStart>
<ID>0</ID>
<Iterations>3</Iterations>
</IterationStart>
<Pump>
<Duration>00:00:12</Duration>
<Frequency>10</Frequency>
</Pump>
<Feed>
<Ratio>3</Ratio>
</Feed>
<Incubate>00:00:10</Incubate>
<Acquire />
<IterationEnd>0</IterationEnd>
</Program>
</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/instrument-control/Config_Files/191119_config_E14.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\config\validator.xsd">
	<Configuration>
		<Microscope>
			<Objective>4</Objective>
			<Filter>BF</Filter>
			<Prism>Ocular</Prism>
			<Intensity>0.0</Intensity>
			<Exposure>50</Exposure>
		</Microscope>
	</Configuration>
	<Loop>
		<Duration>00:12:00</Duration>
		<Image>
			<Prefix>testIMG</Prefix>
			<AcquisitionInterval>00:04:00</AcquisitionInterval>
			<SaveDir>./TestImages/</SaveDir>
		</Image>
		<Microscope>
			<Objective>20</Objective>
			<Filter>BF</Filter>
			<Prism>Camera</Prism>
			<Intensity>9.5</Intensity>
			<Exposure>50</Exposure>
		</Microscope>
		<Microscope>
			<Objective>20</Objective>
			<Filter>GFP</Filter>
			<Prism>Camera</Prism>
			<Intensity>2.5</Intensity>
			<Exposure>150</Exposure>
		</Microscope>
		<Position>
			<X>60415.1</X>
			<Y>40337.1</Y>
			<Focus>419.78</Focus>
		</Position>
		<Position>
			<X>57455.3</X>
			<Y>43292.3</Y>
			<Focus>419.78</Focus>
		</Position>
		<Position>
			<X>57455.3</X>
			<Y>43292.3</Y>
			<Focus>408.78</Focus>
		</Position>
		<Program>
			<Pump>
				<Duration>00:00:10.0000</Duration>
				<Frequency>7</Frequency>
			</Pump>
			<Pump>
				<Duration>00:00:20.0000</Duration>
				<Frequency>5</Frequency>
			</Pump>
		</Program>
	</Loop>
</Measurement>

=== lauflulu/PeriodDoubling/instrument-control/Config_Files/200303_TestProgram_DilutionSeries_0.1-0.7.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Measurement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\e14user\Documents\LabVIEW software\GitRepo\lib\Config\validator.xsd"><Loop>
<Duration>05:00:00</Duration>
<Image>
<Prefix>DilSeries</Prefix>
<AcquisitionInterval>00:00:01</AcquisitionInterval>
<SaveDir>C:\Users\e14user\Documents\LabVIEW software\GitRepo\Test_N_Eval_Images\200303_DilsSeries</SaveDir>
</Image>
<Microscope>
<Objective>10</Objective>
<Filter>BF</Filter>
<Prism>Side</Prism>
<Intensity>25.0</Intensity>
<Exposure>50</Exposure>
</Microscope>
<Microscope>
<Objective>10</Objective>
<Filter>GFP</Filter>
<Prism>Side</Prism>
<Intensity>20.0</Intensity>
<Exposure>50</Exposure>
</Microscope>
<Position>
<X>-89.800</X>
<Y>-645.700</Y>
<Focus>426.90</Focus>
</Position>
<Position>
<X>-89.800</X>
<Y>-2567.100</Y>
<Focus>421.65</Focus>
</Position>
<Position>
<X>-89.800</X>
<Y>-4436.100</Y>
<Focus>421.65</Focus>
</Position>
<Position>
<X>-89.800</X>
<Y>-6295.200</Y>
<Focus>421.65</Focus>
</Position>
<Position>
<X>-89.800</X>
<Y>-8225.100</Y>
<Focus>421.65</Focus>
</Position>
<Position>
<X>120.800</X>
<Y>-10210.400</Y>
<Focus>421.65</Focus>
</Position>
<Position>
<X>120.800</X>
<Y>-12060.400</Y>
<Focus>421.65</Focus>
</Position>
<Position>
<X>120.800</X>
<Y>-13949.900</Y>
<Focus>421.65</Focus>
</Position>
<Program>
<IterationStart>
<ID>0</ID>
<Iterations>10</Iterations>
</IterationStart>
<IterationStart>
<ID>1</ID>
<Iterations>30</Iterations>
</IterationStart>
<ChangeReagent>
<Duration>00:00:05</Duration>
<ReagentNr>1</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>10</Ratio>
<Ring>2</Ring>
</Feed>
<Feed>
<Ratio>20</Ratio>
<Ring>3</Ring>
</Feed>
<Feed>
<Ratio>30</Ratio>
<Ring>4</Ring>
</Feed>
<Feed>
<Ratio>40</Ratio>
<Ring>5</Ring>
</Feed>
<Feed>
<Ratio>50</Ratio>
<Ring>6</Ring>
</Feed>
<Feed>
<Ratio>60</Ratio>
<Ring>7</Ring>
</Feed>
<Feed>
<Ratio>70</Ratio>
<Ring>8</Ring>
</Feed>
<Pump>00:04:10</Pump>
<Incubate>00:01:00</Incubate>
<Acquire />
<Incubate>00:01:00</Incubate>
<IterationEnd>1</IterationEnd>
<ChangeReagent>
<Duration>00:00:10</Duration>
<ReagentNr>2</ReagentNr>
</ChangeReagent>
<Feed>
<Ratio>100</Ratio>
<Ring>2</Ring>
</Feed>
<Feed>
<Ratio>100</Ratio>
<Ring>3</Ring>
</Feed>
<Feed>
<Ratio>100</Ratio>
<Ring>4</Ring>
</Feed>
<Feed>
<Ratio>100</Ratio>
<Ring>5</Ring>
</Feed>
<Feed>
<Ratio>100</Ratio>
<Ring>6</Ring>
</Feed>
<Feed>
<Ratio>100</Ratio>
<Ring>7</Ring>
</Feed>
<Feed>
<Ratio>100</Ratio>
<Ring>8</Ring>
</Feed>
<Pump>00:02:00</Pump>
<IterationEnd>0</IterationEnd>
</Program>
</Loop>
</Measurement>
